CREATE TABLE tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(2000) NOT NULL,
    priority VARCHAR(50) NOT NULL CHECK (priority IN ('BAIXA', 'MEDIA', 'ALTA', 'CRITICA')),
    status VARCHAR(50) NOT NULL CHECK (status IN ('ABERTO', 'EM_ATENDIMENTO', 'AGUARDANDO_SOLICITANTE', 'RESOLVIDO', 'CANCELADO')),
    solution VARCHAR(2000),
    opened_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    sla_deadline TIMESTAMP NOT NULL,
    resolved_at TIMESTAMP,
    requester_id BIGINT NOT NULL,
    technician_id BIGINT,
    category_id BIGINT NOT NULL,

    FOREIGN KEY (requester_id) REFERENCES users (id),
    FOREIGN KEY (technician_id) REFERENCES users (id),
    FOREIGN KEY (category_id) REFERENCES categories(id)
);